-- Source migrations are embedded from this package copy.
CREATE TABLE IF NOT EXISTS groups (id INTEGER PRIMARY KEY, name TEXT NOT NULL, telegram_chat_id INTEGER NOT NULL UNIQUE, timezone TEXT NOT NULL, dashboard_slug TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, telegram_user_id INTEGER NOT NULL UNIQUE, username TEXT, first_name TEXT, last_name TEXT, last_seen_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS group_members (group_id INTEGER NOT NULL REFERENCES groups(id), user_id INTEGER NOT NULL REFERENCES users(id), active INTEGER NOT NULL DEFAULT 1, role TEXT NOT NULL DEFAULT 'member', roast_enabled INTEGER NOT NULL DEFAULT 1, joined_at TEXT NOT NULL, last_seen_at TEXT, PRIMARY KEY(group_id,user_id));
CREATE TABLE IF NOT EXISTS messages (id INTEGER PRIMARY KEY, group_id INTEGER NOT NULL REFERENCES groups(id), telegram_chat_id INTEGER NOT NULL, telegram_message_id INTEGER NOT NULL, user_id INTEGER REFERENCES users(id), sent_at TEXT NOT NULL, kind TEXT NOT NULL, text TEXT, media_group_id TEXT, reply_to_message_id INTEGER, created_at TEXT NOT NULL, UNIQUE(telegram_chat_id,telegram_message_id));
CREATE INDEX IF NOT EXISTS messages_context_idx ON messages(group_id,user_id,sent_at);
CREATE TABLE IF NOT EXISTS user_contexts (group_id INTEGER NOT NULL REFERENCES groups(id), user_id INTEGER NOT NULL REFERENCES users(id), summary TEXT NOT NULL, tags_json TEXT NOT NULL DEFAULT '[]', last_source_message_at TEXT, updated_at TEXT NOT NULL, PRIMARY KEY(group_id,user_id));
CREATE TABLE IF NOT EXISTS events (id INTEGER PRIMARY KEY, group_id INTEGER NOT NULL REFERENCES groups(id), kind TEXT NOT NULL, title TEXT NOT NULL, description TEXT, location TEXT, starts_at TEXT NOT NULL, ends_at TEXT, timezone TEXT NOT NULL, all_day INTEGER NOT NULL DEFAULT 0, rrule TEXT, status TEXT NOT NULL DEFAULT 'active', created_by_user_id INTEGER REFERENCES users(id), source_type TEXT NOT NULL, dedupe_key TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT);
CREATE INDEX IF NOT EXISTS events_lookup_idx ON events(group_id,status,starts_at); CREATE UNIQUE INDEX IF NOT EXISTS events_dedupe_idx ON events(group_id,dedupe_key) WHERE deleted_at IS NULL;
CREATE TABLE IF NOT EXISTS event_sources (id INTEGER PRIMARY KEY,event_id INTEGER NOT NULL REFERENCES events(id),source_type TEXT NOT NULL,telegram_chat_id INTEGER,telegram_message_id INTEGER,external_id TEXT,raw_text TEXT,created_at TEXT NOT NULL,UNIQUE(telegram_chat_id,telegram_message_id),UNIQUE(source_type,external_id));
CREATE TABLE IF NOT EXISTS tags (id INTEGER PRIMARY KEY,name TEXT NOT NULL UNIQUE); CREATE TABLE IF NOT EXISTS event_tags (event_id INTEGER NOT NULL REFERENCES events(id),tag_id INTEGER NOT NULL REFERENCES tags(id),PRIMARY KEY(event_id,tag_id));
CREATE TABLE IF NOT EXISTS reminders (id INTEGER PRIMARY KEY,group_id INTEGER NOT NULL REFERENCES groups(id),creator_user_id INTEGER REFERENCES users(id),target_user_id INTEGER REFERENCES users(id),text TEXT NOT NULL,remind_at TEXT NOT NULL,timezone TEXT NOT NULL,rrule TEXT,next_fire_at TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',telegram_source_message_id INTEGER,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS pending_intents (group_id INTEGER NOT NULL REFERENCES groups(id),user_id INTEGER NOT NULL REFERENCES users(id),intent_type TEXT NOT NULL,payload_json TEXT NOT NULL DEFAULT '{}',expires_at TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(group_id,user_id,intent_type));
CREATE TABLE IF NOT EXISTS jobs (id INTEGER PRIMARY KEY,kind TEXT NOT NULL,payload_json TEXT NOT NULL,run_at TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',attempts INTEGER NOT NULL DEFAULT 0,locked_at TEXT,last_error TEXT,dedupe_key TEXT UNIQUE,created_at TEXT NOT NULL,updated_at TEXT NOT NULL); CREATE INDEX IF NOT EXISTS jobs_due_idx ON jobs(status,run_at);
CREATE TABLE IF NOT EXISTS change_log (id INTEGER PRIMARY KEY AUTOINCREMENT,group_id INTEGER NOT NULL REFERENCES groups(id),kind TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT NOT NULL,payload_json TEXT NOT NULL,created_at TEXT NOT NULL);
